name: Release executable

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Install .NET Framework 4.0 Developer Pack
      run: choco install netfx-4.0-devpack -y
  
    - name: Build solution
      run: msbuild src\RDPKeepAlive.sln /p:Configuration=Release /t:Build

    - name: Remove PDB files
      run: del /Q src\RDPKeepAlive\bin\Release\*.pdb 2>nul
      shell: cmd

    - name: List output files
      run: dir src\RDPKeepAlive\bin\Release\
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: RDPKeepAlive
        path: src\RDPKeepAlive\bin\Release\RDPKeepAlive.exe

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: src/RDPKeepAlive/bin/Release/RDPKeepAlive.exe
